version: '3.8'

services:
  chatterdb:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
    expose:
      - 5432
  api:
    build: .
    ports:
      - 5432:5432
    environment:
      - PORT=5432
      - DATABASE_URL=chatterdb
    depends_on:
      - chatterdb
